export const theme = {
  colors: {
    backgroundBase: "#020617",
    backgroundSurface: "#FFFFFF0F",
    backgroundSurfaceSoft: "#FFFFFF0A",
    backgroundSurfacePressed: "#FFFFFF19",
    backgroundSurfaceStrong: "#FFFFFF1F",
    backgroundAccentBlue: "#3B82F61F",
    backgroundTrack: "#02061780",
    backgroundGlow: "#0F172AF2",
    borderSubtle: "#FFFFFF14",
    borderSoft: "#FFFFFF0F",
    borderAccent: "#60A5FA4D",
    orbPrimary: "#4F46E559",
    orbSecondary: "#2563EB2E",
    glowWarm: "#FBBF242E",
    shadowBlue: "#3b82f6",
    textPrimary: "#ffffff",
    textSecondary: "#dbeafe",
    textMuted: "#cbd5e1",
    textSubtle: "#94a3b8",
    textDim: "#64748b",
    accentSky: "#60a5fa",
    accentSkyStrong: "#3b82f6",
    accentCyan: "#7dd3fc",
    accentAmber: "#f59e0b",
    iconSun: "#fbbf24",
    iconCloud: "#d1d5db",
    iconCloudSoft: "#e5e7eb",
    iconRain: "#60a5fa",
    iconRainStrong: "#38bdf8",
    iconNight: "#a5b4fc",
  },
} as const;

export type Theme = keyof typeof theme.colors;
