#!/usr/bin/env sh

message="$(cat "$1")"
subject="$(printf '%s\n' "$message" | sed -n '1p')"
requiredPattern='^(test|add|cut|fix|bump|make|start|stop|refactor|reformat|optimise|document|merge|feat|chore|wip|config|remove): .*$'

if ! printf '%s\n' "$subject" | grep -Eq "$requiredPattern"; then
  echo "-"
  echo "-"
  echo "-"
  echo "🚨 Wrong commit message!"
  echo "The commit message must have this format:"
  echo "<verb in imperative mood>: <what was done>"
  echo "Allowed verbs in imperative mood: test, add, cut, fix, bump, make, start, stop, refactor, reformat, optimise, document, merge, feat, chore, wip, config, remove"
  echo "Example: add: login button"
  echo "-"
  echo "Your commit message was:"
  printf '%s\n' "$message"
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
fi
